spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: isubash
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:library_schema.sql
